PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX tennet: <http://data.tennet.eu/def/>
PREFIX base:  <https://w3id.org/def/basicsemantics-owl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>

#Notes: No grouopName here as a small change to the name will make the sheet enormous

SELECT DISTINCT ?specUri ?specCode ?specName ?specText ?activityUri ?activityName ?documentUri ?documentName ?interneToelichting ?owner ?projectCategorie
WHERE {
  ?specUri skos:prefLabel ?specName .
  ?specUri rdf:type ?conceptualSpecUri .
  ?conceptualSpecUri skos:prefLabel ?conceptualSpecName .
  ?conceptualSpecUri rdfs:subClassOf nen2660:Requirement .
  OPTIONAL{
  ?specUri skos:notation ?specCode .
  ?specUri rdf:value ?specText .
  }
  OPTIONAL {
	?parentSpecificationUri tennet:isDerivedIn ?specUri .
	?parentSpecificationUri skos:prefLabel ?parentSpecificationName .
  }
  OPTIONAL{
  ?activityUri nen2660:hasRequirement ?specUri .
  ?activityUri rdfs:subClassOf* nen2660:Activity .
  ?activityUri skos:prefLabel ?activityName .
  }
  OPTIONAL {
    #What About refersTo?
    ?documentUri nen2660:hasRequirement ?specUri .
    ?documentUri rdfs:subClassOf* nen2660:InformationObject .
    ?documentUri skos:prefLabel ?documentName .
  }
  OPTIONAL {
      ?groupUri skos:member ?specUri .
      ?groupUri skos:prefLabel ?groupName .
      ?groupUri rdf:type skos:Collection .
  }
  OPTIONAL {
      ?specUri ?toelichtingProp ?interneToelichting .
      ?toelichtingProp a owl:AnnotationProperty .
      ?toelichtingProp  skos:prefLabel "Interne toelichting" .
  }
  OPTIONAL {
      ?specUri ?ownerProp ?owner .
      ?ownerProp a owl:AnnotationProperty .
      ?ownerProp  skos:prefLabel "Owner" .
  }
  OPTIONAL {
      ?specUri ?pojectCategorieProp ?projectCategorie.
      ?pojectCategorieProp a owl:AnnotationProperty .
      ?pojectCategorieProp  skos:prefLabel "Project categorie" .
  }
  OPTIONAL {
      ?specUri ?rpojectAanpassingenProp ?projectAanpassingen.
      ?projectAanpassingen a owl:AnnotationProperty .
      ?projectAanpassingen  skos:prefLabel "Project aanpassingen" .
  }
}
ORDER BY ?conceptualSpecName ?specCode ?specName